{===============================================================================

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

===============================================================================}

const
  libEGL = 'libEGL.so';
  libGLESv2 = 'libGLESv2.so';
  libc = 'libc.so';
  liblog = 'liblog.so';
  libandroid = 'libandroid.so';
  libdl = 'libdl.so';
  libm = 'libm.so';
